### PR TITLE
Contact Page

### PR DESCRIPTION
**Pull request by Vrushalipagar31**

### CODE REVIEW

**Comment by Vrushalipagar31** [comment]
check now

**Comment by Vrushalipagar31** [comment]
Since the page is longer, we can't hide y-axis scroll bar. Still I've made the changes.

**Comment by Vrushalipagar31** [comment]
Done. aur new PR bhi issue kr diya hai

**Review by bhawanibytes — COMMENTED** [review]
Seems All good!

**Comment by Vrushalipagar31** [comment]
Okay will do it by Tomorrow

**Comment by Vrushalipagar31** [comment]
exactly kya karna hai?
can you please explain something

**Pull request merged**
